### ISSUE TITLE
Invalid gzip header build script

### ISSUE THREAD

**Issue by Techno-Fox** [shakacode/vosk-rs#2]
Trying the fix, i ran into another error relating to the build script.

`
error: failed to run custom build command for `vosk v0.1.0 (https://github.com/shakacode/vosk-rs#82862744)`

Caused by:
  process didn't exit successfully: `target/debug/build/vosk-f17f6333003832d0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=dylib=lapack
  cargo:rerun-if-changed=cbits/vosk.h
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to iterate over archive

  Caused by:
      invalid gzip header', .cargo/git/checkouts/vosk-rs-a04e65f7663b4a01/8286274/build.rs:54:42
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
     1: core::panicking::panic_fmt
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
     2: core::result::unwrap_failed
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
     4: build_script_build::main
               at ./build.rs:54:9
     5: core::ops::function::FnOnce::call_once
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

`

**Comment by andreytkachenko** [comment]
It looks like you did not run `cargo clean` before building that after update. I cannot reproduce the bug

**Comment by Techno-Fox** [comment]
Running cargo clean, then cargo build, gives me this error.

`
Caused by:
  process didn't exit successfully: `target/debug/build/vosk-f17f6333003832d0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=dylib=lapack
  cargo:rerun-if-changed=cbits/vosk.h
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unexpected response code 301 for http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.6.7.tar.gz', ~/.cargo/git/checkouts/vosk-rs-a04e65f7663b4a01/8286274/build.rs:53:46
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
     1: core::panicking::panic_fmt
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
     2: core::result::unwrap_failed
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
     4: build_script_build::main
               at ./build.rs:53:9
     5: core::ops::function::FnOnce::call_once
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
`
